AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31
- AWS::CodeStar

Parameters:
  ProjectId:
    Type: String
    Description: AWS CodeStar projectID used to associate new resources to team members

Resources:
  HelloWorldApi:
    Type: AWS::Serverless::Api
    Properties:
      StatgName: qa

  HelloWorld:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.huirongxing.demo.ci.handler.HelloWorldHandler::handleRequest
      Runtime: java8
      Timeout: 30
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
      Events:
        HelloWorldApi:
          Type: Api
          Properties:
            RestApiId: !Ref HelloWorldApi
            Path: /hello
            Method: GET

