AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31
- AWS::CodeStar

Parameters:
  ProjectId:
    Type: String
    Description: AWS CodeStar projectID used to associate new resources to team members

Resources:
  HelloWorld:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.huirongxing.demo.ci.handler.HelloWorldHandler::handleRequest
      Runtime: java8
      Timeout: 30
      FunctionName: HelloWorld
      AutoPublishAlias: qa
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
      Events:
        GetHello:
          Type: Api
          Properties:
            Name: HelloWorldApi
            Path: /hello
            Method: GET
            Stage: qa


